### ISSUE TITLE
Cannot set property 'options' of undefined 

### ISSUE THREAD

**Issue by yankeyhotel** [SachaG/meteor-spin#26]
I might be doing this wrong, but I am getting `Cannot set property 'options' of undefined` everytime I try to set the `Meteor.Spinner.options = { /* props */ }`

Saw this, but not sure if its the same issue. #4

**Comment by yankeyhotel** [comment]
So I got help figuring this out. The settings need to be added in the `Meteor.startup` function in the client.

**Comment by ThadeuLuz** [comment]
Hmm.. not necessarily. I just tossed it anywhere in the client folder and it works. This error is probably from trying to run it on the server.
