### ISSUE TITLE
Please add a license so that others can use this package

### ISSUE THREAD

**Issue by levinse** [SachaG/meteor-spin#35]
Could you please add a license so that others can use this package? Publishing software without a license means that anyone attempting to use it would be in violation of copyright. If you could please add a MIT or other distribution-friendly license, that would be appreciated!

Thanks

**Comment by SachaG** [comment]
Well, you shouldn't really be using this package, it doesn't really have a reason to exist now that Meteor supports NPM packages out of the box.

**Comment by levinse** [comment]
I hear you but unfortunately the application is still on meteor 1.2! Hoping to upgrade it shortly but we're undergoing some due diligence right now so all 3rd party components are being audited :)

**Comment by SachaG** [comment]
Done: https://github.com/SachaG/meteor-spin/blob/master/license.md
